# see: https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

inherit_from:
  - .rubocop/overrides.yml
  - .rubocop/strict.yml

AllCops:
  # This keeps rubocop output quiet
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1.4
