url: 'https://danielramirez.xyz'

plugins:
  - jekyll-postcss

postcss:
  # Disabling cache is needed for Tailwind CSS’s JIT engine.
  # Without this, the server would need to restart after each change.
  cache: false

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
